name: genteel_store
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  dio: ^5.5.0+1
  dartz: ^0.10.1
  equatable: ^2.0.5
  skeletonizer: ^1.3.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  currency_formatter: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/font/

  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/font/AirbnbCereal_W_Bd.otf
        - asset: assets/font/AirbnbCereal_W_Bk.otf
        - asset: assets/font/AirbnbCereal_W_Blk.otf
        - asset: assets/font/AirbnbCereal_W_Lt.otf
        - asset: assets/font/AirbnbCereal_W_Md.otf
        - asset: assets/font/AirbnbCereal_W_XBd.otf
